ProjectAsakura/Bayshore

src/modules/game.ts
writing this PR on a phone fear meeeeeeeeeeeeeeeeeee
=> add hardcoded car profile, works in terminal but wont work in the drive cab????

package.json, src/index.ts, src/modules/game.ts, yarn.lock
Added dotenv to the requirements, fixed bug with time attack saving
=> Added dotenv to the requirements, fixed bug with time attack saving

.gitignore, LICENSE, README.md, prisma/migrations/20220721011310_rg_region_map_score/migration.sql, prisma/schema.prisma, src/modules/game.ts
-Ghost Battle no longer disconnected but still bugged
-Crown Ghost Battle not working (disconnected)
-Dress Up Working and saved
-Ghost Region Map Score Working and Saved
-Search Ghost by Level Working
-Search Ghost by Name not Working (disconnected)
-Change Full Tune Ticket (now default ghostLevel is 10)
-No Ghost Movement Saving
-Add rgRegionMapScore to Car table
=> some ghost battle feature fixed but still bugged

src/modules/game.ts
=> revert window sticker change

config.example.json, src/config.ts, src/modules/game.ts
custom colour editable in the terminal and saved
discarded card obatainable every n*100 play and saved
ghost trophy
---
**config.json**
-  "giveMeterReward": 0
_0 = give meter reward is off
1 = give meter reward is on_
=> fix custom color, discarded card and add feature

src/modules/game.ts, src/modules/startup.ts
temporary fix for crown ghost failed to load ghost trail
=> fix crown ghost saving bug

src/modules/ghost.ts, src/modules/startup.ts, src/modules/terminal.ts, src/modules/users.ts, src/util/games/story.ts
stclearbits not resetting to 0 after clearing story 20,40,80,...
=> fix story bug

src/modules/cars.ts, src/modules/ghost.ts, src/modules/ghost_ocm.ts, src/modules/users.ts, src/util/common.ts, src/util/games/games_util/ghost_history.ts, src/util/games/ghost.ts, src/util/games/ghost_ocm.ts, src/util/games/story.ts, start.bat
=> ocm fix ranking

src/modules/cars.ts, src/util/games/story.ts
=> fix story clear bits not resetting.. haiyaaa

src/modules/terminal.ts
=> fix terminal ocm ranking

src/modules/cars.ts, src/modules/ghost_ocm.ts, src/modules/terminal.ts
trying to fix register ocm ghost from terminal
tested works from my local
also need to delete all the `GhostRegisteredFromTerminal` record data first i think (manually)... coz i changed the data inserted and how to read it
=> trying to fix register ocm ghost from terminal

src/modules/cars.ts, src/modules/resource.ts, src/util/games/story.ts
=> fix crown list order and story nuke bug when clearing story that already cleared

src/modules/users.ts, src/util/games/time_attack.ts
i hate u register app pop up
that pop up after tapping banapass on terminal
=> no register app pop up

src/modules/cars.ts, src/util/games/story.ts
=> change how to read challengers for faster loading

src/modules/cars.ts, src/modules/ghost_ocm.ts, src/modules/startup.ts, src/modules/terminal.ts, src/modules/users.ts, src/util/games/ghost.ts, src/util/games/versus.ts, src/util/ghost/ghost_history.ts, src/util/ghost/ghost_save_trail.ts, src/util/ghost/ghost_trail.ts
- fix vs star saving, sometimes it becomes 0 agian
- bare bone save_screenshot url request
- change OCM sorting to by competitionId
- fix how to read OCM HoF trail data
=> fix star saving (sometimes become 0), barebone save_screenshot, fix ocm sorting, hopefully fix ocm hof

src/modules/ghost.ts, src/modules/ghost_ocm.ts, src/modules/terminal.ts, src/util/games/ghost.ts, src/util/ghost/ghost_trail.ts
=> fix broken gtWing saving, OCM HoF again

src/modules/cars.ts, src/modules/ghost.ts
=> fix undefined properties (reading carId), fix ghost list

src/modules/ghost/functions.ts, src/modules/resource/crown_list.ts, src/modules/users.ts
=> prevent crashing if ghost region id is not between 1 and 47

.gitignore, config.example.json, src/allnet.ts, src/config.ts, src/modules/cars.ts, src/modules/cars/functions.ts, src/modules/game.ts, src/modules/game/functions.ts, src/modules/ghost/ghost_history.ts, src/modules/resource.ts, src/modules/users.ts
=> randomizer, default place regionid must not 0, blocking vanilla tp chip id

src/modules/cars.ts, src/modules/cars/functions.ts, src/modules/game/time_attack.ts, src/modules/ghost.ts, src/modules/ghost/functions.ts, src/modules/ghost/ghost_ocm.ts, src/modules/startup/functions.ts, src/modules/terminal.ts, src/modules/users.ts
- limit terminal ocm ranking to 150
- fix ghost search by region
- prevent TA record more than 20 minutes from being submitted
=> limit terminal ocm ranking to 150, fix ghost search by region, preven TA record more than 20 minutes

src/modules/game/time_attack.ts, src/modules/terminal.ts, start.bat
- update TA cheated time detection
- fix terminal ocm rank
- md only show top 50 leaderboard
- end ocm only show top 10 leaderboard
=> Important fix

config.example.json, src/modules/terminal.ts, src/modules/terminal/scratch.ts, src/modules/users.ts
_no idea on how it suddenly broken (for some ppl)_
=> trying to fix terminal scratch

src/modules/cars.ts, src/modules/cars/functions.ts, src/modules/terminal.ts
terminal ocm
- fix number of participant
- end ocm show top 25
- md show top 100
block special car from being regged with CE
=> fix terminal ocm ranking, blocking some car reg

flake.nix, src/modules/game.ts, src/modules/ghost/ghost_history.ts
_didnt expect about double speed fps_
=> change force finish detection threshold

src/modules/cars.ts, src/modules/cars/functions.ts, src/modules/game.ts, src/modules/game/ghost.ts, src/modules/game/versus.ts, src/modules/ghost/ghost_ocm.ts, src/modules/ghost_ocm.ts
right after clicking the merge button in ProjectAsakura/Bayshore#80 i realised this is a bad idea for security reasons
=> Revert "allow player rename"

src/modules/cars/functions.ts, src/modules/game.ts, src/modules/game/ghost.ts, src/modules/game/versus.ts, src/modules/ghost/ghost_ocm.ts, src/modules/ghost_ocm.ts
=> some fix and proper force finish handling(hopefully)

src/modules/users.ts
With reference to #86. Here is the PR making the fix. Thank you.
=> Fixed AIME REGEX issue

src/modules/cars/functions.ts, src/modules/game.ts, src/modules/game/functions.ts, src/modules/game/ghost.ts, src/modules/ghost_ocm.ts, src/modules/users.ts
just some minor stuff, hope to get it roll out on live server asap
- prevent saving when user is banned
- little removal for unneeded stuff
=> some fixes

config.example.json, src/config.ts, src/modules/cars.ts, src/modules/game.ts, src/modules/game/ghost.ts, src/modules/users.ts
last pr got approved before i can include this in
=> auto delete ghost trail function
